### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by AydarLukmanov**
Fix example

### CODE REVIEW

**Review by Rakoth — APPROVED** [review]
Thanks!

**Comment by doomspork** [comment]
Thank you @AydarLukmanov 😀

**Comment by AydarLukmanov** [comment]
You are welcome! ( It's my most appreciative commit so far :) ).

**Comment by doomspork** [comment]
I hope you can find other opportunities to contribute @AydarLukmanov 😁

**Pull request merged**
