### PR TITLE
Rename project to "Slime"

### PR DESCRIPTION
**Pull request by lpil**
Requires the repo to be renamed, travis to be updated, and a new package to be released on hex.

I guess the same would need to be done for the other projects.

Would it make sense to also make a github organisation here?

### CODE REVIEW

**Comment by doomspork** [comment]
If I'm not mistaken another Hex package already has "Slime".  We'll need to reach out and make sure the owner is still on board with handing over the account.

**Comment by doomspork** [comment]
I reached out to the Slime owner.  I will keep you updated.

On a separate note, @lpil would you like to be added as a project collaborator?  My only request is that major changes go through PR.

**Comment by lpil** [comment]
I'd love to be a collaborator. Happy to continue to work in PRs.

**Comment by doomspork** [comment]
Hooray :tada: You've been added @lpil, cheers!

**Comment by lpil** [comment]
Thanks :)

**Comment by doomspork** [comment]
We're green lighted on using Slime.  Can you rebase this branch and see if it's merge-able?

**Comment by lpil** [comment]
Rebased.

**Comment by henrik** [comment]
Louis, awesome work on all this!

**Pull request merged**
