### PR TITLE
Replace generic Branch struct

### PR DESCRIPTION
**Pull request by doomspork**
RFC @lpil — Took a quick stab at #76, let me know your thoughts.

### CODE REVIEW

**Comment by lpil** [comment]
I was wondering if we should use records instead, but the values for each type vary a lot, so I think this is better.

I don't like the name branch. I prefer Element or Node as that's the terminology used when talking about HTML.

**Comment by doomspork** [comment]
I'll make the change from Branch to Node today.  :+1:

**Comment by doomspork** [comment]
Renaming complete.  Let me know what you think @lpil.

**Comment by lpil** [comment]
Looks good to go!

**Pull request merged**
