### PR TITLE
Update github links post slime-lang creation

### PR DESCRIPTION
**Pull request by lpil**

### CODE REVIEW

**Comment by doomspork** [comment]
:+1:

**Comment by doomspork** [comment]
You should have access to TravisCI by way of the org membership.

**Comment by doomspork** [comment]
We might want to submit a PR for AwesomeElixir as well.  Both projects are listed on there and point to my repos.

**Comment by lpil** [comment]
Do you wanna do that or shall I?

**Comment by doomspork** [comment]
You can go for it :grinning:

**Comment by lpil** [comment]
https://github.com/h4cc/awesome-elixir/pull/1428

**Pull request merged**
