### PR TITLE
Remove excess newlines

### LINKED ISSUE #48: Textarea adds blank lines
When I upgrade a project from slim_fast 0.7.0 to 0.9.1, the Slim code

```
textarea id="code" name="code" = "foo"
```

that previously on 0.7.0 would output

``` html
<textarea id="code" name="code">foo</textarea>
```

now on 0.9.1 outputs

``` html
<textarea id="code" name="code">foo
</textarea>
```

This leads to extra linebreaks in the received input, that were not intended.

### PR DESCRIPTION
**Pull request by doomspork**
RFC @henrik — This addresses the original issues #35 sought to fix while fixing the issue you reported in #48.

Closes #48.

### CODE REVIEW

**Comment by doomspork** [comment]
Once this is given the :+1: I'll release it along with #50 as `v0.10`

**Comment by doomspork** [comment]
Sorry @Rakoth I should have cc'd you in the original PR.

**Comment by Rakoth** [comment]
@doomspork This is make sense :+1:

**Comment by henrik** [comment]
Looks great! Once it's released I'll try it in my project.

**Comment by henrik** [comment]
Tried in my project and it worked fine.

I bumped the version to 0.9.2 but I don't have rights to publish. If you're OK giving that to me, the command is:

```
mix hex.owner add slim_fast henrik@nyh.se
```

**Comment by henrik** [comment]
Oh, I missed the comment about releasing a `v0.10`. Sorry about that. The closed tag thing does warrant a minor version bump (though semver says anything goes before 1.0).

Changed the version to 0.10.0 now.

**Comment by doomspork** [comment]
Thanks @henrik!  Both you and @Rakoth have been added to Hex.  Feel free to publish away.

@Rakoth I used the email address in your GH profile, let me know if you'd like me to change it to something else.

Thanks again :+1:

**Comment by henrik** [comment]
Published!

**Comment by doomspork** [comment]
:boom: :+1:

**Pull request merged**
