### PR TITLE
Explicitly return variable values from if/unless

### PR DESCRIPTION
**Pull request by aptinio**
Fixes Elixir 1.3 warnings about unsafe variables
for being set inside a case/cond/receive/if/&&/||.

### CODE REVIEW

**Comment by Rakoth** [comment]
👍

**Comment by doomspork** [comment]
Thank you @aptinio!  @lpil any thoughts before we merge?

**Comment by lpil** [comment]
Seems fine to me

**Comment by aptinio** [comment]
You're welcome! Thank you for all your work on this.

**Pull request merged**
