### PR TITLE
README: Differences to Ruby Slim

### PR DESCRIPTION
**Pull request by henrik**

### CODE REVIEW

**Comment by doomspork** [comment]
This is great.  Thanks for taking the initiative of getting this documented.  :+1:

**Comment by henrik** [comment]
@doomspork Happy to contribute – this stuff confused me a bit when I started out, so hopefully this helps the next person :)

While we're on this topic… I wonder if it could make any sense to come up with an entirely new name for this templating language/engine. There is [Jade](http://jade-lang.com/) for JS/Node for example, which is very Slim-like, but not exactly. Which also describes SlimFast :)

If we did go that route, we could also consider stealing good ideas from Jade. I like how you can use a `.` for a block of text, for example: http://jade-lang.com/reference/plain-text/

The README could mention both Slim and Jade, so people searching for "Slim for Elixir" and such would probably find their way here anyway.

What do you think? Just a not-very-considered idea. @joakimk, any thoughts?

**Comment by doomspork** [comment]
@henrik I think that's a pretty clever idea and something I can get behind.   I'd love to hear from both @Rakoth and @joakimk.  :+1:

While we're on the topic of projects future, would you like join the project/repo as contributor?  I've really appreciated your help making the project better.  I only ask that major changes go through PRs.  Let me know what you think.  Thanks again!

**Comment by henrik** [comment]
Awesome, glad that you like the idea.

I toyed with some names – the best one to my eyes/ears so far is "Slime". "Slim" with an "e" for Elixir. Not taken by any Hex package and doesn't seem to be in use as a templating language.

Sure, I wouldn't mind being a contributor. I suspect I'll only fix occasional small things around the edges, but still.

**Comment by henrik** [comment]
Further research reveals an abandoned(?) partial implementation of a "Slime" templating thing for Elixir: https://github.com/northerner/slime

@northerner, how would you feel about us using that name for this project? If we would decide to rename, and if that's the name we like best.

**Comment by doomspork** [comment]
Great, you're added @henrik.  Let's open an issue and continue the discussion there, sound good?

**Comment by henrik** [comment]
@doomspork Thanks! Yeah, good thinking. Opened an issue: https://github.com/doomspork/slim_fast/issues/55

**Comment by northerner** [comment]
@henrik feel free to use the name, I'm just glad someone is taking on this Slim in Elixir task :+1: 

I had wanted to build a parser that would return valid Elixir AST from slim, the same stuff you get calling `quote`. Maybe it would be possible, but I quickly abandoned it when I realised how much pain it would be to avoid using a custom AST.

**Comment by doomspork** [comment]
@northerner are you still onboard with us using the Slime project name?

Thanks!

**Comment by northerner** [comment]
@doomspork yes, of course. Have no plans to develop my attempt further.

**Pull request merged**
