### PR TITLE
Add a largely meaningless benchmark

### PR DESCRIPTION
**Pull request by lpil**
Heya.

I was curious about performance, so I added a little benchmark.

I'm not really sure this shows us anything useful, but it did make me feel more confident in using this library.

Can we improve this, and is there any value in doing so?

Cheers,
Louis

### CODE REVIEW

**Comment by doomspork** [comment]
@lpil you were busy today! :+1:

@henrik want to take a peek at this?  I know you started on benchmarking previously.

**Comment by henrik** [comment]
Hey,

I just did a quick stab that is probably in an issue comment somewhere :) I think there is a benchmarking issue.

Don't think I'll have the time/inclination to look at this anytime soon I'm afraid :/

**Comment by doomspork** [comment]
Sounds good @henrik.  This looks good to me @lpil, we can always add to it. :+1:

**Comment by lpil** [comment]
Cool, thanks. :)

**Pull request merged**
