### PR TITLE
Fix: doctype followed by empty line

### PR DESCRIPTION
**Pull request by lobo-tuerto**
Add failing test case.

### CODE REVIEW

**Comment by lobo-tuerto** [comment]
Hello @Rakoth I created a PR with a failing test case that illustrates the issue.

If you could kindly provide some pointers on where should I look now to try and fix this (or how) I'd really appreciate it (kinda new to Elixir and this problem space).

I tried to modify the `src/slime_parser.peg.eex` file without success.

I tried adding a `(space? crlf)*` between `doctype?` and `tags?` thinking that would do it, but no success (got a very high number of failing tests).

**Comment by lobo-tuerto** [comment]
Seems like I was able to find a solution to the problem, my previous failing test case is now passing and no new errors were introduced! :)

Still don't understand why I could not just insert a `(space? crlf)*` between `doctype?` and `tags?`.
It worked when I added it at the end of the `doctype` definition, like this:

```peg
doctype <- space? 'doctype' space name:(!eol .)+ eol (space? crlf)*;
```

**Comment by Rakoth** [comment]
Great job, @lobo-tuerto! When you modifying peg grammar, you should change transform functions accordingly (https://github.com/slime-lang/slime/blob/master/lib/slime/parser/transform.ex#L34)

**Comment by lobo-tuerto** [comment]
@Rakoth Hmmm tried fiddling around with the code you pointed me to, but no luck. :(

Is my PR good to go or do I need to modify something at `transform.ex`?

**Comment by Rakoth** [comment]
@lobo-tuerto LGTM, @doomspork any thoughts before merge?

**Comment by doomspork** [comment]
Do we want to get travis passing before we merge @lobo-tuerto / @Rakoth?

**Comment by Rakoth** [comment]
Master build also failing, so we can fix it separately

**Comment by lobo-tuerto** [comment]
Yay! my first Elixir code contribution to open source! :D

**Comment by lobo-tuerto** [comment]
Hello guys, when could we expect a patch version update that includes this fix?

**Comment by doomspork** [comment]
Sorry about that @lobo-tuerto! Let me see if there’s anything we need to do first otherwise I’ll cut a release today or tomorrow.

**Comment by lobo-tuerto** [comment]
Hello @doomspork :)

**Pull request merged**
